import type { Metadata } from "next";
import { Host_Grotesk } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { TooltipProvider } from "@/components/ui/tooltip";
import { ClerkProvider } from "@clerk/nextjs";
import { TRPCReactProvider } from "@/trpc/client";
import { Suspense } from "react";
import { ThemeProvider } from "@/components/theme-provider"

const inter = Host_Grotesk({subsets:['latin']});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
    suppressHydrationWarning
      lang="en"
      className={cn("h-full", "antialiased", "font-sans", inter.className)}
    >
      <body 
      suppressHydrationWarning
      className="min-h-full flex flex-col">
        <TRPCReactProvider>
           <ClerkProvider>
          <TooltipProvider>
          <Suspense>
                 <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
              {children}
              </ThemeProvider>
          </Suspense>
          </TooltipProvider>
         </ClerkProvider>
        </TRPCReactProvider>
        </body>
    </html>
  );
}
